import 'package:cloud_functions/cloud_functions.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:firebase_core/firebase_core.dart';

import 'chat_operation_exception.dart';

String cleanErrorMessage(
  Object? error, {
  String fallback = 'errors.unexpected',
}) {
  final fallbackMessage = _translateMessage(fallback);
  if (error == null) return fallbackMessage;


  if (error is ChatOperationException) {
    return _translateMessage(error.messageKey);
  }

  if (error is FirebaseFunctionsException) {
    final detailsKey = _extractErrorKey(error.details);
    if (detailsKey != null && detailsKey.isNotEmpty) {
      return _translateMessage(detailsKey);
    }

    final message = error.message?.trim();
    if (message != null && message.isNotEmpty) {
      return _translateMessage(message);
    }

    switch (error.code) {
      case 'unauthenticated':
        return tr('errors.session_expired');
      case 'permission-denied':
        return tr('errors.permission_denied');
      case 'unavailable':
        return tr('errors.service_unavailable');
      case 'deadline-exceeded':
        return tr('errors.deadline_exceeded');
      default:
        return fallbackMessage;
    }
  }

  if (error is FirebaseException) {
    final message = error.message?.trim();
    if (message != null && message.isNotEmpty) {
      return _translateMessage(message);
    }

    switch (error.code) {
      case 'permission-denied':
      case 'unauthorized':
        return tr('errors.data_permission_denied');
      case 'unavailable':
        return tr('errors.service_connection_failed');
      default:
        break;
    }
  }

  var text = error.toString().trim();
  if (text.isEmpty) return fallbackMessage;

  const prefixes = [
    'Exception: ',
    'StateError: ',
    'FirebaseException: ',
  ];

  for (final prefix in prefixes) {
    if (text.startsWith(prefix)) {
      text = text.substring(prefix.length).trim();
    }
  }

  text = text.replaceFirst(RegExp(r'^\[cloud_functions/[^\]]+\]\s*'), '');
  text = text.replaceFirst(RegExp(r'^\[firebase_storage/[^\]]+\]\s*'), '');
  text = text.replaceFirst(RegExp(r'^\[cloud_firestore/[^\]]+\]\s*'), '');

  return text.trim().isEmpty ? fallbackMessage : _translateMessage(text.trim());
}


String? _extractErrorKey(Object? details) {
  if (details is Map) {
    final raw = details['errorKey'] ?? details['translationKey'] ?? details['messageKey'];
    final key = raw?.toString().trim();
    return key == null || key.isEmpty ? null : key;
  }

  return null;
}

const Map<String, String> _legacyTranslationKeyByMessage = {
  '4 أرقام': 'pin.text_4_digits',
  'Chat Messages': 'notifications.chat_channel_name_2',
  'Notifications for chat messages': 'notifications.chat_channel_desc_2',
  'PDF أو Office': 'chat.pdf_office',
  'PDF أو غيره': 'legacy.pdf_other',
  'PIN_PEPPER غير مضبوط': 'legacy.pin_secret_not_configured',
  'Unknown Device': 'common.unknown_device',
  'appProjectId مطلوب عند استخدام scope = project': 'legacy.appprojectid_required_when_scope_project',
  'eventId مطلوب': 'legacy.eventid_required',
  'groupId مطلوب': 'legacy.groupid_required',
  'groupId مطلوب لحدث الغرفة': 'legacy.groupid_required_group_event',
  'sessionId مطلوب': 'legacy.sessionid_required',
  'uid مطلوب': 'legacy.uid_required',
  'أبدِ اهتمامك': 'events.mark_interested',
  'أدخل 4 أرقام': 'pin.enter_4_digits',
  'أدخل اسم الحدث': 'legacy.enter_event_title',
  'أدخل اسمًا واضحًا ومختصرًا': 'home.enter_clear_concise_name',
  'أدخل الاسم الكامل': 'auth.enter_full_name_2',
  'أدخل الرقم الجامعي': 'auth.enter_university_id',
  'أدخل الرقم الجامعي وكلمة السر': 'auth.enter_university_id_password',
  'أدخل الرمز القديم': 'pin.enter_old_pin',
  'أدخل تفاصيل الحدث': 'legacy.enter_event_details',
  'أدخل رقم الهاتف': 'auth.enter_phone_number_2',
  'أدخل رمز PIN': 'pin.enter_pin',
  'أدخل سؤال الاستبيان': 'chat.enter_poll_question',
  'أدخل كلمة السر': 'auth.enter_password',
  'أدخل كلمة السر الجديدة': 'auth.enter_new_password',
  'أدخل كلمة السر القديمة': 'auth.enter_old_password',
  'أدخل كلمة السر المؤقتة': 'auth.enter_temporary_password_2',
  'أدخل مكان الحدث': 'legacy.enter_event_location',
  'أدخل ملاحظات إضافية': 'legacy.enter_extra_notes',
  'أدخل نص الخيار': 'chat.enter_option_text',
  'أرشفة غروب': 'legacy.archive_group',
  'أعد إدخال الرمز الجديد': 'pin.re_enter_new_pin',
  'أعد إدخال كلمة السر الجديدة': 'auth.re_enter_new_password',
  'أعد إدخال نفس الرمز للتأكيد': 'pin.re_enter_same_pin_confirm',
  'أعد تسجيل الدخول ثم حاول مرة أخرى': 'auth.errors.reauth_required',
  'أقصى نطاق مسموح هو سنة واحدة': 'legacy.maximum_allowed_range_one_year',
  'أمس': 'chat.yesterday',
  'إجمالي السجلات': 'auth.bulk_import.total_records',
  'إجمالي المصوتين: {}': 'chat.total_voters_value',
  'إدارة الأعمال': 'legacy.business_administration',
  'إدارة الطلاب': 'legacy.student_management',
  'إدارة الغروبات': 'legacy.group_management',
  'إرسال': 'common.send',
  'إرسال إشعار إداري': 'legacy.send_admin_notification',
  'إرسال الاستبيان': 'chat.send_poll',
  'إرسال التسجيل الصوتي': 'legacy.send_voice_recording',
  'إرسال الصورة': 'chat.send_image',
  'إرسال الفيديو': 'chat.send_video',
  'إرسال الملف': 'chat.send_file',
  'إرسال فيديو': 'legacy.send_video',
  'إرسال محتوى': 'chat.send_content',
  'إرفاق': 'chat.attach',
  'إزالة': 'chat.remove',
  'إزالة حساب طالب': 'legacy.remove_student_account',
  'إزالة عضو من الغروب': 'legacy.remove_group_member',
  'إشعار': 'legacy.notification',
  'إضافة أعضاء للغروب': 'legacy.add_group_members',
  'إضافة جماعية JSON أو Excel': 'auth.bulk_import.title',
  'إضافة خيار': 'chat.add_option',
  'إضافة مستخدم': 'home.add_user',
  'إعادة الإرسال': 'chat.resend',
  'إعادة المحاولة': 'common.retry',
  'إعادة تعيين PIN': 'legacy.reset_pin',
  'إعادة تعيين كلمة المرور': 'legacy.reset_password',
  'إعادة تفعيل حساب طالب': 'legacy.reactivate_student_account',
  'إعادة توجيه': 'chat.forward',
  'إعادة توجيه الرسالة': 'chat.forward_message',
  'إعداد الكتابة غير صالح': 'legacy.invalid_write_permission_setting',
  'إغلاق': 'common.close',
  'إلغاء': 'common.cancel',
  'إلغاء أرشفة غروب': 'legacy.unarchive_group',
  'إلغاء التسجيل': 'chat.cancel_recording',
  'إلغاء الحدث': 'events.cancel_event',
  'إلغاء حدث': 'legacy.cancel_event',
  'إلى تاريخ': 'dashboard.date',
  'إنشاء': 'home.create',
  'إنشاء استبيان': 'chat.create_poll',
  'إنشاء الحدث': 'legacy.create_event_2',
  'إنشاء تصويت': 'legacy.create_vote',
  'إنشاء حدث': 'legacy.create_event',
  'إنشاء طالب': 'legacy.create_student',
  'إنشاء غروب': 'legacy.create_group',
  'إنشاء مجموعة': 'home.create_group',
  'ابحث عن المجموعات...': 'search.search_groups_hint',
  'ابحث عن مجموعة': 'search.search_group_hint',
  'اترك لإلغاء التسجيل': 'legacy.release_cancel_recording',
  'اترك للإلغاء': 'chat.release_cancel',
  'اختر الغرفة المستهدفة': 'legacy.choose_target_group',
  'اختر اللغة': 'common.language.choose_language',
  'اختر مجموعة أخرى لإعادة التوجيه': 'legacy.choose_another_group_forward',
  'اختر مجموعة مسموح لك بالإرسال إليها': 'chat.choose_group_allowed_send',
  'اختر ملفًا أولًا': 'auth.bulk_import.choose_file_first',
  'اختر ملفًا ثم ابدأ الرفع، وستظهر حالة التنفيذ في الأسفل.': 'auth.bulk_import.instructions',
  'اختر نوع السجل والفترة الزمنية ثم اضغط تطبيق الفلاتر': 'dashboard.choose_log_type_date_range_apply_filters',
  'اختر نوع المرفق المناسب للمحادثة': 'chat.choose_attachment_type_chat',
  'اختر وقت حدث صالح': 'legacy.choose_valid_event_time',
  'اختيار ملف': 'auth.bulk_import.choose_file',
  'اختيار من المعرض': 'legacy.choose_gallery',
  'استبيان': 'chat.poll',
  'استعادة حساب طالب': 'legacy.restore_student_account',
  'استغرقت العملية وقتًا طويلًا. حاول مرة أخرى': 'legacy.operation_took_too_long_try_again',
  'استلم': 'chat.receipts.delivered',
  'اسحب لليسار للإلغاء': 'legacy.swipe_left_cancel',
  'اسم الحدث': 'legacy.event_title',
  'اسم الحدث طويل جدًا': 'legacy.event_name_too_long',
  'اسم الغرفة غير صالح': 'legacy.invalid_group_room_name',
  'اسم المجموعة': 'home.group_name',
  'اسم المجموعة طويل جدًا': 'home.group_name_too_long',
  'اسم المجموعة فارغ': 'legacy.group_name_empty',
  'اسم المجموعة مطلوب': 'home.group_name_required',
  'اسم الملف طويل جدًا': 'legacy.file_name_too_long',
  'اضغط للإيقاف': 'legacy.tap_stop',
  'اضغط للتشغيل': 'legacy.tap_play',
  'اضغط للتشغيل أو الإيقاف': 'legacy.tap_play_pause',
  'اكتب السؤال هنا': 'chat.type_question_here',
  'اكتب رسالة.': 'legacy.type_message',
  'اكتب رسالة...': 'chat.type_message',
  'اكتمل الرفع مع وجود بعض الأخطاء': 'auth.bulk_import.upload_completed_some_errors',
  'اكتملت عملية الرفع': 'auth.bulk_import.upload_completed',
  'الأحداث': 'events.title',
  'الأحداث المهتم بها': 'legacy.interested_events',
  'الأرشيف': 'archive.title',
  'الأعضاء:': 'group_info.members_title',
  'الإشعارات': 'notifications.title',
  'الإنجليزية': 'common.language.english',
  'الاسم الكامل': 'common.full_name',
  'الاسم الكامل طويل جدًا': 'auth.full_name_too_long',
  'الاسم طويل جدًا': 'legacy.name_too_long',
  'البوابة': 'web.portal',
  'البيانات غير صالحة': 'legacy.invalid_data',
  'البيانات غير مكتملة': 'legacy.incomplete_data',
  'التسجيل قصير جدًا': 'chat.recording_too_short',
  'التقاط صورة': 'chat.take_photo',
  'التقاط من الكاميرا': 'legacy.take_camera',
  'الجامعة الوطنية الخاصة': 'branding.app_name',
  'الجلسة المعلقة غير صالحة': 'legacy.pending_session_invalid',
  'الحدث غير موجود': 'events.event_not_found',
  'الحساب غير موجود في قاعدة البيانات': 'auth.errors.account_not_found_in_database',
  'الخادم مشغول أو تم تجاوز الحصة، حاول بعد قليل': 'legacy.server_busy_quota_was_exceeded_try_again',
  'الخدمة غير متاحة حاليا، حاول مرة أخرى': 'legacy.service_unavailable_try_again_2',
  'الخدمة غير متاحة حاليًا. حاول مرة أخرى': 'legacy.service_unavailable_try_again',
  'الخيار {}': 'chat.option_value',
  'الدفعات المنجزة': 'auth.bulk_import.completed_batches',
  'الدور': 'common.role',
  'الرجاء إدخال الاسم الكامل': 'auth.enter_full_name',
  'الرجاء إدخال الرقم الجامعي': 'auth.enter_university_id_2',
  'الرجاء إدخال رقم الهاتف': 'auth.enter_phone_number',
  'الرجاء إدخال كلمة السر': 'auth.enter_password_2',
  'الرجاء إدخال كلمة السر المؤقتة': 'auth.enter_temporary_password',
  'الرسالة طويلة جدًا': 'legacy.message_too_long',
  'الرقم الجامعي': 'common.student_id',
  'الرقم الجامعي أو كلمة السر غير صحيحة': 'auth.errors.invalid_credentials',
  'الرقم الجامعي طويل جدًا': 'auth.university_id_too_long',
  'الرقم الجامعي مسجل بالفعل': 'legacy.university_id_already_registered',
  'الرقم الجامعي معرف ثابت ولا يمكن تعديله بعد إنشاء الحساب': 'legacy.university_id_fixed_cannot_changed_after_account',
  'الرمز الجديد': 'pin.new_pin',
  'الرمز الجديد يجب أن يكون 4 أرقام': 'pin.new_pin_must_4_digits',
  'الرمز القديم': 'pin.old_pin',
  'الرمز القديم غير صحيح': 'legacy.old_pin_incorrect',
  'الرمز القديم يجب أن يكون 4 أرقام': 'pin.old_pin_must_4_digits',
  'الرمزان الجديدان غير متطابقين': 'pin.new_pins_do_not_match',
  'الرمزان غير متطابقين': 'pin.pins_do_not_match',
  'السنة غير صالحة': 'legacy.invalid_year',
  'الشهر غير صالح': 'legacy.invalid_month',
  'الصور': 'chat.photos',
  'الصيدلة': 'legacy.pharmacy',
  'العربية': 'common.language.arabic',
  'العمود {} غير موجود في ملف Excel': 'auth.bulk_import.column_value_missing_excel_file',
  'الغرفة المستهدفة': 'legacy.target_group',
  'الفيديو': 'chat.video',
  'القسم': 'common.department',
  'القسم المستهدف: {}': 'legacy.target_department_value',
  'القسم طويل جدًا': 'legacy.department_too_long',
  'القسم غير محدد': 'home.department_not_set',
  'الكاميرا': 'chat.camera',
  'اللغة': 'common.language.title',
  'المتبقي: {} ثانية': 'chat.remaining_value_second_s',
  'المتبقي: {} دقيقة {} ثانية': 'chat.remaining_value_minute_s_value_second_s',
  'المتبقي: {} ساعة {} دقيقة': 'chat.remaining_value_hour_s_value_minute_s',
  'المتبقي: {} يوم {} ساعة': 'chat.remaining_value_day_s_value_hour_s',
  'المجموعات': 'home.groups',
  'المجموعة أو الرسالة غير موجودة': 'legacy.group_message_was_not_found',
  'المجموعة غير موجودة': 'legacy.group_not_found',
  'المجموعة لا تحتوي أعضاء صالحين': 'legacy.group_has_no_valid_members',
  'المحددون': 'dashboard.selected',
  'المدير: {}': 'group_info.admin_format',
  'المرفق غير متاح للحفظ': 'legacy.attachment_not_available_save',
  'المرفق غير متوفر لإعادة التوجيه': 'legacy.attachment_not_available_forwarding',
  'المستخدم غير موجود': 'legacy.user_not_found',
  'المشرف: {}': 'search.admin_format',
  'الملاحظات طويلة جدًا': 'legacy.notes_too_long',
  'الملف الشخصي': 'profile.title',
  'الملف المحلي غير متوفر لإعادة الإرسال': 'legacy.local_file_not_available_retry',
  'الملف المحلي غير موجود. أعد اختيار الملف وأرسله مرة أخرى': 'legacy.local_file_no_longer_exists_choose_file',
  'الملف غير صالح': 'chat.invalid_file',
  'النظام': 'legacy.system',
  'الهندسة المدنية': 'legacy.civil_engineering',
  'الوضع الداكن': 'home.dark_mode',
  'اليوم': 'chat.today',
  'انتهاء استيراد الطلاب': 'legacy.finish_student_import',
  'انتهت الجلسة. سجل الدخول مرة أخرى': 'auth.errors.session_expired_sign_in_again',
  'انتهت الجلسة، أعد تسجيل الدخول': 'auth.errors.session_expired_sign_in_again_short',
  'انتهت صلاحية الدخول دون إنترنت، اتصل بالإنترنت مرة واحدة للتحقق من رمز PIN': 'pin.offline_pin_unlock_has_expired_connect_internet',
  'انتهى الاستبيان': 'chat.poll_ended',
  'انضم الآن': 'search.join_now',
  'انقل إدارة المجموعة أولًا قبل حذف المدير': 'legacy.transfer_group_administration_before_removing_admin',
  'بانتظار الشبكة': 'chat.message_status.waiting_network',
  'بحث عن المجموعات': 'search.title',
  'بحث عن مجموعات': 'home.find_groups',
  'بدء استيراد الطلاب': 'legacy.start_student_import',
  'بدأت عملية الرفع، يمكنك متابعة التقدم أدناه': 'auth.bulk_import.upload_started',
  'بدون وقت انتهاء': 'chat.no_expiry_time',
  'بوابة الجامعة': 'branding.portal_title',
  'بيئة أكاديمية أنيقة، موثوقة، وسريعة.': 'branding.login_hint',
  'بيانات التعريف غير مكتملة': 'legacy.profile_identifiers_incomplete',
  'بيانات الجلسة غير مكتملة': 'legacy.session_data_incomplete',
  'بيانات الحدث غير مكتملة': 'legacy.event_data_incomplete',
  'بيانات المستخدم': 'auth.user_data',
  'بيانات ناقصة': 'legacy.missing_data',
  'تأكيد الإلغاء': 'events.confirm_cancellation',
  'تأكيد الحذف': 'chat.delete_confirm_title',
  'تأكيد الرمز الجديد': 'pin.confirm_new_pin',
  'تأكيد رمز PIN': 'pin.confirm_pin',
  'تأكيد كلمة السر الجديدة': 'auth.confirm_new_password',
  'تاريخ النهاية يجب أن يكون بعد تاريخ البداية': 'legacy.end_date_must_after_start_date',
  'تجميد حساب طالب': 'legacy.suspend_student_account',
  'تحميل المزيد': 'dashboard.load_more',
  'تسجيل الخروج': 'auth.logout',
  'تسجيل الدخول': 'auth.sign',
  'تسجيل الطالب': 'auth.register_student',
  'تسجيل صوتي': 'chat.voice_recording',
  'تسجيل طالب جديد': 'auth.register_new_student',
  'تصويت سريع': 'chat.quick_poll',
  'تعديل الحدث': 'events.edit_event',
  'تعديل بيانات طالب': 'legacy.update_student_profile',
  'تعديل بيانات غروب': 'legacy.update_group_profile',
  'تعديل حدث': 'legacy.update_event',
  'تعديل صورة الغروب': 'legacy.update_group_icon',
  'تعذر إكمال عملية الرفع. حاول مرة أخرى': 'auth.bulk_import.could_not_complete_import_try_again',
  'تعذر إلغاء الحدث حاليا': 'events.errors.cancel_failed_now',
  'تعذر إنشاء الحدث حاليا': 'events.errors.create_failed_now',
  'تعذر الاتصال بالخدمة حاليًا': 'legacy.unable_connect_service_right',
  'تعذر التحقق من رمز PIN، تأكد من الاتصال ثم حاول مرة أخرى': 'pin.could_not_verify_pin_check_connection_try',
  'تعذر التحقق من رمز PIN، حاول مرة أخرى': 'pin.could_not_verify_pin_try_again',
  'تعذر التحميل': 'legacy.unable_load',
  'تعذر الحصول على بيانات المستخدم': 'auth.errors.user_data_unavailable',
  'تعذر الحفظ، حاول مرة أخرى': 'chat.could_not_save_try_again',
  'تعذر تجهيز صفحة إنشاء الحدث. تحقق من الاتصال ثم حاول مجددًا': 'legacy.could_not_prepare_event_creation_page_check',
  'تعذر تحديث الاهتمام بالحدث حاليا': 'events.errors.interest_update_failed_now',
  'تعذر تحديد اسم المستخدم': 'search.could_not_determine_user_name',
  'تعذر تحديد البريد الداخلي للحساب': 'auth.errors.internal_email_unavailable',
  'تعذر تحميل إحصائيات لوحة التحكم حاليا': 'legacy.could_not_load_dashboard_statistics_right',
  'تعذر تحميل إعدادات الإشعارات': 'group_info.could_not_load_notification_settings',
  'تعذر تحميل الأحداث حاليا': 'events.errors.load_failed_now',
  'تعذر تحميل الأرشيف. تحقق من الاتصال ثم حاول مجددًا': 'legacy.could_not_load_archive_check_connection_try',
  'تعذر تحميل التصويتات حاليًا': 'chat.could_not_load_votes_right',
  'تعذر تحميل الرسائل. تحقق من الاتصال ثم حاول مجددًا': 'legacy.could_not_load_messages_check_connection_try',
  'تعذر تحميل الصفحة الرئيسية. تحقق من الاتصال ثم حاول مجددًا': 'home.could_not_load_home_page_check_connection',
  'تعذر تحميل الصورة': 'common.could_not_load_image',
  'تعذر تحميل المجموعات المتاحة': 'chat.unable_load_available_groups',
  'تعذر تحميل المجموعات. تحقق من الاتصال ثم حاول مجددًا': 'home.could_not_load_groups_check_connection_try',
  'تعذر تحميل المحادثة. تحقق من الاتصال ثم حاول مجددًا': 'legacy.could_not_load_chat_check_connection_try',
  'تعذر تحميل الملف الشخصي. تحقق من الاتصال ثم حاول مجددًا': 'profile.could_not_load_profile_check_connection_try',
  'تعذر تحميل اهتمامات الأحداث': 'events.unable_load_event_interests',
  'تعذر تحميل بطاقة الحدث': 'chat.could_not_load_event_card',
  'تعذر تحميل بيانات المستخدم. تحقق من الاتصال ثم حاول مجددًا': 'legacy.could_not_load_user_data_check_connection',
  'تعذر تحميل تفاصيل الحدث. تحقق من الاتصال ثم حاول مجددًا': 'events.could_not_load_event_details_check_connection',
  'تعذر تحميل حملات الإشعارات': 'legacy.could_not_load_notification_campaigns',
  'تعذر تحميل سجل العمليات': 'legacy.could_not_load_audit_logs',
  'تعذر تحميل قائمة الأعضاء': 'group_info.errors.members_load_failed',
  'تعذر تحميل معلومات المجموعة. تحقق من الاتصال ثم حاول مجددًا': 'group_info.errors.load_failed_check_connection',
  'تعذر تسجيل التصويت حاليًا': 'chat.unable_submit_vote_right',
  'تعذر تسجيل المستخدم. حاول مرة أخرى': 'auth.could_not_register_user_try_again',
  'تعذر تشغيل الرسالة الصوتية': 'legacy.could_not_play_voice_message',
  'تعذر تشغيل الفيديو': 'common.could_not_play_video',
  'تعذر تعديل الحدث حاليا': 'events.errors.update_failed_now',
  'تعذر تعديل العضوية': 'chat.could_not_update_membership',
  'تعذر رفع الملف: تأكد أنك عضو في المجموعة': 'legacy.could_not_upload_file_make_sure_member',
  'تعذر عرض الصورة': 'legacy.could_not_display_image',
  'تعذر فتح التطبيق. تحقق من الاتصال ثم حاول مجددًا': 'auth.could_not_open_app_check_connection_try',
  'تعذر فتح المرفق مؤقتًا': 'legacy.could_not_open_attachment_temporarily',
  'تعذر فتح المرفق: لا تملك صلاحية الوصول': 'legacy.could_not_open_attachment_do_not_have',
  'تعذر فتح الملف': 'legacy.could_not_open_file',
  'تعذر فتح الملف المحفوظ': 'chat.could_not_open_saved_file',
  'تعيين رمز PIN': 'pin.set_pin',
  'تعيين كلمة سر جديدة': 'auth.set_new_password',
  'تعيين كمدير أساسي': 'legacy.set_as_primary_admin',
  'تغيير رمز PIN': 'pin.change_pin',
  'تغيير كلمة السر': 'profile.change_password',
  'تفاصيل الحدث': 'events.event_details',
  'تفاصيل الحدث طويلة جدًا': 'legacy.event_details_too_long',
  'تم إلغاء الحدث بنجاح': 'events.event_was_cancelled_successfully',
  'تم إلغاء كتم المجموعة': 'group_info.unmute_success',
  'تم إلغاء هذا الحدث': 'events.event_has_been_cancelled',
  'تم إنشاء الحدث بنجاح': 'legacy.event_was_created_successfully',
  'تم إنشاء المجموعة': 'home.group_created',
  'تم الإلغاء': 'legacy.cancelled',
  'تم الانضمام بنجاح': 'search.join_success',
  'تم الحفظ في جهازك': 'attachments.saved_to_device',
  'تم تجاوز 3 محاولات، تم تسجيل الخروج': 'pin.text_3_attempts_exceeded_have_been_signed_out',
  'تم تجميد حسابك من قبل الإدارة، يرجى مراجعة المسؤول': 'auth.errors.account_suspended_by_admin',
  'تم تجهيز مهمة الرفع': 'auth.bulk_import.upload_job_ready',
  'تم تحديث اهتمامك بالحدث': 'events.interest_event_has_been_updated',
  'تم تحديث صورة المجموعة': 'group_info.group_image_updated',
  'تم تحميل {} سجل': 'auth.bulk_import.value_records_loaded',
  'تم تسجيل المستخدم بنجاح': 'auth.register.success',
  'تم تسجيل خروجك لأن الحساب دخل من جهاز آخر': 'legacy.were_signed_out_because_account_was_opened',
  'تم تسجيل مقطع صوتي. هل تريد إرساله؟': 'legacy.voice_clip_has_been_recorded_do_want',
  'تم تعديل الحدث بنجاح': 'legacy.event_was_updated_successfully',
  'تم تغيير رمز PIN بنجاح': 'pin.pin_changed_successfully',
  'تم تغيير كلمة السر بنجاح': 'auth.password_changed_successfully',
  'تم تغيير كلمة السر، لكن تعذر تحديث حالة الحساب. أعد تسجيل الدخول بكلمة السر الجديدة': 'legacy.password_was_changed_but_account_state_could',
  'تم حذف الرسالة': 'chat.message_deleted',
  'تم حذف المجموعة': 'group_info.group_deleted',
  'تم حظر المحاولة مؤقتًا، حاول لاحقًا': 'auth.errors.too_many_attempts_try_later',
  'تم طرد العضو': 'group_info.member_removed',
  'تم فتح المجموعة': 'group_info.group_unlocked',
  'تم قفل المجموعة': 'group_info.group_locked',
  'تم قفل المحاولات مؤقتاً، حاول لاحقاً': 'legacy.attempts_temporarily_locked_try_again_later',
  'تم كتم إشعارات المجموعة': 'group_info.mute_success',
  'تم مغادرة المجموعة': 'search.leave_success',
  'تم نسخ الرسالة': 'chat.message_copied',
  'تمت أرشفة المجموعة': 'group_info.archive_success',
  'تمت إزالة حسابك من النظام': 'auth.errors.account_removed',
  'تمت إعادة تفعيل المجموعة': 'group_info.unarchive_success',
  'تمت إعادة توجيه الرسالة': 'chat.message_forwarded',
  'تمت الإضافة': 'auth.bulk_import.added',
  'تمت قراءة الملف بنجاح': 'auth.bulk_import.file_read_success',
  'ث': 'chat.s',
  'جار التحقق...': 'pin.verifying',
  'جار التحميل': 'legacy.loading',
  'جار التهيئة...': 'common.initializing',
  'جار الحفظ...': 'legacy.saving',
  'جار تحميل الصورة': 'common.loading_image',
  'جار تحميل الفيديو': 'common.loading_video',
  'جار فتح البوابة': 'web.opening_portal',
  'جاري التشغيل': 'legacy.playing',
  'جارٍ الإرسال': 'chat.message_status.sending',
  'جارٍ الإنشاء': 'home.creating',
  'جارٍ التجهيز': 'legacy.preparing',
  'جارٍ التحميل': 'common.loading',
  'جارٍ التسجيل': 'chat.recording',
  'جارٍ الحفظ': 'common.saving',
  'جارٍ رفع الطلاب...': 'auth.bulk_import.uploading_students',
  'جاهز': 'legacy.ready',
  'حالة الاستيراد الجماعي': 'auth.bulk_import.status_title',
  'حتى 3 دقائق': 'chat.up_3_minutes',
  'حجم الملف أكبر من المسموح': 'chat.file_size_exceeds_allowed_limit',
  'حدث': 'events.scope_event',
  'حدث جامعي': 'events.scope_university',
  'حدث خطأ أثناء تحميل الإحصائيات': 'legacy.error_occurred_while_loading_statistics',
  'حدث خطأ أثناء تسجيل الدخول': 'auth.errors.login_unexpected',
  'حدث خطأ أثناء تغيير كلمة السر': 'auth.error_occurred_while_changing_password',
  'حدث خطأ غير متوقع. حاول مرة أخرى': 'legacy.something_went_wrong_try_again',
  'حدث خطأ غير متوقع: {}': 'legacy.unexpected_error_occurred_value',
  'حدث غرفة': 'events.scope_group',
  'حدث قسم': 'events.scope_department',
  'حدد نطاق الحدث': 'legacy.select_event_scope',
  'حدد وقت انتهاء صالح': 'chat.choose_valid_expiry_time',
  'حذف': 'common.delete',
  'حذف المجموعة': 'group_info.delete_group',
  'حذف غروب': 'legacy.delete_group',
  'حفظ التعديل': 'pin.save_changes',
  'حفظ التعديلات': 'legacy.save_changes',
  'حفظ على الجهاز': 'chat.save_device',
  'حفظ كلمة السر': 'auth.save_password',
  'خيار التصويت طويل جدًا': 'chat.poll_option_too_long',
  'خيارات': 'legacy.options',
  'دكتور': 'roles.doctor',
  'رسالة': 'chat.attachment.message',
  'رسالة صوتية': 'chat.attachment.voice_message',
  'رسالة محددة': 'legacy.selected_message',
  'رفع الطلاب': 'auth.upload_students',
  'رقم الهاتف': 'common.phone',
  'رقم الهاتف طويل جدًا': 'auth.phone_number_too_long',
  'رقم الهاتف غير صالح': 'legacy.invalid_phone_number',
  'رقم الهاتف مستخدم بالفعل': 'legacy.phone_number_already_use',
  'رمز PIN غير صحيح، المتبقي {} محاولات': 'pin.incorrect_pin_value_attempts_remaining',
  'رمز PIN يجب أن يكون 4 أرقام': 'pin.pin_must_4_digits',
  'سؤال الاستبيان': 'chat.poll_question',
  'سؤال التصويت يجب ألا يتجاوز 120 حرفًا': 'chat.poll_question_must_not_exceed_120_characters',
  'سبب حالة الحساب طويل جدًا': 'legacy.account_status_reason_too_long',
  'ستصلك إشعارات الرسائل الجديدة من هذه المجموعة.': 'group_info.unmute_notifications_description',
  'صورة': 'chat.attachment.image',
  'طالب': 'roles.student',
  'طالب/مستخدم': 'legacy.student_user',
  'طب الاسنان': 'legacy.dentistry',
  'طرد': 'group_info.remove',
  'طرد عضو': 'group_info.remove_member',
  'طرد عضو من الغروب': 'legacy.kick_group_member',
  'عدد خيارات التصويت يجب أن يكون بين 2 و 6': 'chat.poll_options_must_between_2_6',
  'عرض الحدث': 'chat.view_event',
  'على مستوى الجامعة': 'legacy.university_level',
  'على مستوى الغرفة': 'legacy.group_level',
  'على مستوى القسم': 'legacy.department_level',
  'عملية غير معروفة': 'legacy.unknown_action',
  'عميد': 'roles.dean',
  'غرفة المحادثة': 'chat.chat_room',
  'غروب': 'legacy.group',
  'غير متاح الآن': 'legacy.not_available',
  'غير مفعّل': 'home.disabled',
  'فتح التطبيق': 'pin.unlock_app',
  'فشل': 'common.failed',
  'فشل إنشاء صورة مصغّرة للفيديو': 'legacy.failed_create_video_thumbnail',
  'فشل الإرسال': 'legacy.send_failed',
  'فشل تسجيل الدخول': 'auth.errors.login_failed',
  'فشل تغيير رمز PIN': 'pin.failed_change_pin',
  'فشل تغيير كلمة السر': 'auth.errors.change_password_failed',
  'فشل حفظ رمز PIN، أعد تسجيل الدخول ثم حاول مرة أخرى': 'pin.failed_save_pin_sign_again_try_again',
  'فشلت عملية الرفع': 'auth.bulk_import.upload_failed',
  'فعّل إذن الميكروفون لإرسال رسالة صوتية': 'chat.enable_microphone_permission_send_voice_message',
  'فقط المشرف يمكنه الكتابة في هذه المجموعة': 'legacy.only_admin_can_write_group',
  'فيديو': 'chat.attachment.video',
  'قد تحتاج إلى إنشاء فهرس Firestore للأحداث': 'legacy.may_need_create_firestore_index_events',
  'قرأ': 'chat.receipts.read',
  'قسم {}': 'home.department_format',
  'قيد التنفيذ': 'common.in_progress',
  'كتم إشعارات المجموعة': 'group_info.mute_notifications',
  'كل الأحداث': 'legacy.all_events',
  'كل الأقسام': 'legacy.all_categories',
  'كلمة السر': 'auth.password',
  'كلمة السر الجديدة': 'auth.new_password',
  'كلمة السر الجديدة ضعيفة': 'auth.errors.new_password_weak',
  'كلمة السر الجديدة يجب أن تكون 6 أحرف على الأقل': 'validation.new_password_min_6',
  'كلمة السر القديمة': 'auth.old_password',
  'كلمة السر القديمة غير صحيحة': 'auth.errors.old_password_incorrect',
  'كلمة السر المؤقتة': 'auth.temporary_password',
  'كلمة السر طويلة جدًا': 'validation.password_too_long',
  'كلمة السر يجب أن تكون 6 أحرف على الأقل': 'validation.password_min_6',
  'كلمة المرور طويلة جدًا': 'validation.password_too_long_2',
  'كلمتا السر الجديدتان غير متطابقتين': 'auth.new_passwords_do_not_match',
  'لا توجد أحداث متاحة حاليا': 'legacy.no_events_available',
  'لا توجد أحداث مهتم بها': 'legacy.no_interested_events_yet',
  'لا توجد رسائل بعد': 'chat.no_messages_yet',
  'لا توجد عملية نشطة': 'auth.bulk_import.no_active_operation',
  'لا توجد مجموعات لديك حتى الآن': 'home.do_not_have_any_groups_yet',
  'لا توجد مجموعات مؤرشفة': 'legacy.no_archived_groups',
  'لا توجد مجموعات متاحة ضمن قسمك': 'search.no_groups_available_department',
  'لا توجد مجموعات متاحة لإعادة التوجيه': 'chat.no_groups_available_forwarding',
  'لا توجد نتائج مطابقة': 'search.no_matching_results',
  'لا يمكن إلغاء حدث انتهى موعده': 'legacy.cannot_cancel_event_has_already_ended',
  'لا يمكن الانضمام إلى مجموعة مؤرشفة': 'legacy.cannot_join_archived_group',
  'لا يمكن التفاعل مع هذا الحدث': 'legacy.cannot_interact_event',
  'لا يمكن تعديل حدث تم إلغاؤه': 'legacy.cannot_edit_cancelled_event',
  'لا يمكن تعيين رمز جديد هنا، استخدم تغيير الرمز بإدخال الرمز القديم': 'legacy.cannot_set_new_pin_here_use_change',
  'لا يمكن تغيير حالة حساب مدير النظام': 'legacy.cannot_change_system_admin_account_status',
  'لا يمكن تغيير قسم المجموعة مع وجود أعضاء من قسم مختلف. (فقط مدير النظام يمكنه القيام بذلك تلقائياً)': 'legacy.group_department_cannot_changed_while_it_has',
  'لا يمكن طرد مدير المجموعة': 'legacy.cannot_remove_group_admin',
  'لا يمكن لمدير المجموعة مغادرتها قبل تعيين مدير آخر': 'legacy.group_admin_cannot_leave_before_assigning_another',
  'لا يمكنك إدارة مجموعات خارج قسمك': 'legacy.cannot_manage_groups_outside_department',
  'لا يمكنك الإرسال إلى هذه المجموعة': 'legacy.cannot_send_messages_group',
  'لا يمكنك الانضمام لهذه المجموعة لأن القسم مختلف': 'legacy.cannot_join_group_because_department_different',
  'لا يمكنك نقل المستخدم إلى قسم آخر': 'legacy.cannot_move_user_another_department',
  'لا يوجد أعضاء صالحون للإضافة': 'legacy.there_no_valid_members_add',
  'لا يوجد أعضاء في هذه المجموعة': 'group_info.empty_members',
  'لا يوجد رمز PIN محفوظ محليا، اتصل بالإنترنت مرة واحدة': 'pin.no_pin_saved_locally_connect_internet_once',
  'لا يوجد مستخدم مسجل دخول': 'auth.errors.no_signed_in_user',
  'لا يوجد مستلمون صالحون ضمن نطاق صلاحياتك': 'legacy.there_no_valid_recipients_within_permission_scope',
  'لست عضوًا في المجموعة الأصلية': 'legacy.not_member_source_group',
  'لست عضوًا في هذه المجموعة': 'legacy.not_member_group',
  'لم يتم اختيار ملف': 'auth.bulk_import.no_file_was_selected',
  'لم يتم اختيار ملف بعد': 'auth.bulk_import.no_file_selected_yet',
  'لم يتم الإرسال': 'chat.message_status.not_sent',
  'لم يتم العثور على بيانات الحساب': 'profile.account_data_was_not_found',
  'لم يتم العثور على قسم للمستخدم': 'search.no_department_was_found_user',
  'لم يتم تعيين رمز PIN بعد': 'legacy.pin_has_not_been_set_yet',
  'لم يستلم': 'chat.receipts.not_delivered',
  'لن تصلك إشعارات من هذه المجموعة، وستبقى الرسائل والعدادات تعمل.': 'group_info.mute_notifications_description',
  'ليس لديك صلاحية': 'legacy.do_not_have_permission',
  'ليس لديك صلاحية إلغاء هذا الحدث': 'legacy.do_not_have_permission_cancel_event',
  'ليس لديك صلاحية إنشاء حدث جامعي': 'legacy.do_not_have_permission_create_university_event',
  'ليس لديك صلاحية إنشاء حدث قسم': 'legacy.do_not_have_permission_create_department_event',
  'ليس لديك صلاحية إنشاء حدث لهذه الغرفة': 'legacy.do_not_have_permission_create_event_room',
  'ليس لديك صلاحية إنشاء مجموعات': 'legacy.do_not_have_permission_create_groups',
  'ليس لديك صلاحية تعديل هذا الحدث': 'legacy.do_not_have_permission_edit_event',
  'ليس لديك صلاحية عرض هذا الحدث': 'legacy.do_not_have_permission_view_event',
  'ليس لديك صلاحية لتعديل هذا الحساب': 'legacy.do_not_have_permission_edit_account',
  'ليس لديك صلاحية لتنفيذ هذه العملية': 'legacy.do_not_have_permission_perform_action',
  'ليس لديك صلاحية لحذف هذا الحساب': 'legacy.do_not_have_permission_remove_account',
  'ليس لديك صلاحية للوصول إلى الإحصائيات': 'legacy.do_not_have_permission_access_statistics',
  'ليس لديك صلاحية للوصول إلى هذه البيانات': 'legacy.do_not_have_permission_access_data',
  'ليست لديك صلاحية': 'legacy.do_not_have_permission_2',
  'ليست لديك صلاحية إنشاء أحداث': 'legacy.do_not_have_permission_create_events',
  'ليست لديك صلاحية حذف هذه الرسالة': 'legacy.do_not_have_permission_delete_message',
  'متبقّي': 'chat.remaining',
  'مجموعاتك ورسائلك في مكان واحد': 'home.groups_and_messages_one_place',
  'مجموعة نشر الحدث غير محددة': 'legacy.event_publishing_group_not_specified',
  'مجموعة نشر الحدث غير موجودة': 'legacy.event_publishing_group_was_not_found',
  'محددة': 'chat.selected',
  'مدير المجموعة المحدد غير موجود': 'legacy.selected_group_admin_does_not_exist',
  'مدير المجموعة المحدد غير نشط': 'legacy.selected_group_admin_not_active',
  'مراجعة قبل الإرسال': 'legacy.review_before_sending',
  'مرحبًا، {}': 'home.welcome_user',
  'مسار المرفق غير صالح': 'legacy.invalid_attachment_path',
  'مسار المرفق غير موجود': 'legacy.attachment_path_missing',
  'مسار صورة المجموعة غير صالح': 'legacy.invalid_group_image_path',
  'مستخدم': 'home.user',
  'مستوى السجل غير صالح': 'legacy.invalid_log_level',
  'مشرف': 'roles.supervisor',
  'معاينة الصورة': 'legacy.image_preview',
  'معاينة الفيديو': 'common.video_preview',
  'معلومات المجموعة': 'group_info.title',
  'مفعّل': 'home.enabled',
  'مكان الحدث': 'legacy.event_location',
  'مكان الحدث طويل جدًا': 'legacy.event_location_too_long',
  'مكتمل': 'common.completed',
  'مكتمل جزئيًا': 'auth.bulk_import.partially_completed',
  'ملاحظات': 'legacy.notes',
  'ملخص': 'dashboard.summary',
  'ملخص الاستلام والقراءة': 'chat.delivery_read_summary',
  'ملخص الرسالة': 'chat.receipts.message_summary',
  'ملف': 'chat.attachment.file',
  'ملف Excel فارغ': 'auth.bulk_import.excel_file_empty',
  'ملف Excel لا يحتوي على بيانات': 'auth.bulk_import.excel_file_contains_no_data',
  'ملف JSON يجب أن يكون عبارة عن List': 'auth.bulk_import.json_file_must_list',
  'من المعرض': 'chat.gallery',
  'من تاريخ': 'dashboard.date_2',
  'منصة التواصل الجامعي': 'branding.chat_title',
  'منضم': 'search.joined',
  'مهتم': 'events.interested',
  'مهتمون: {}': 'events.interested_count',
  'موظف': 'roles.employee',
  'موظف رئاسة': 'roles.presidency_employee',
  'موظف قسم': 'roles.department_staff',
  'موعد الحدث يجب أن يكون مستقبليًا': 'legacy.event_time_must_future',
  'موعد الحدث: {}': 'legacy.event_time_value',
  'نسخ': 'chat.copy',
  'نطاق الحدث': 'legacy.event_scope',
  'نطاق الحدث غير صالح': 'legacy.invalid_event_scope',
  'نوع الحساب طويل جدًا': 'legacy.account_type_too_long',
  'نوع الرسالة غير مدعوم لإعادة الإرسال': 'legacy.message_type_cannot_resent',
  'نوع السجل': 'dashboard.log_type',
  'نوع السجل مطلوب': 'legacy.log_type_required',
  'نوع الصورة غير مدعوم': 'chat.unsupported_image_type',
  'نوع الفيديو غير مدعوم': 'chat.unsupported_video_type',
  'نوع الملف الصوتي غير مدعوم': 'chat.unsupported_audio_file_type',
  'نوع الملف غير مدعوم': 'chat.unsupported_file_type',
  'هذا الإجراء متاح فقط على حسابات الطلاب': 'legacy.action_available_only_student_accounts',
  'هذه المجموعة في الأرشيف ولا يمكن الكتابة فيها': 'legacy.group_archived_cannot_written',
  'هل أنت متأكد من حذف هذه المجموعة نهائيًا؟': 'group_info.sure_want_permanently_delete_group',
  'هل تريد إلغاء هذا الحدث؟': 'events.do_want_cancel_event',
  'هل تريد حذف هذه الرسالة من عند الجميع؟': 'chat.delete_message_for_everyone_question',
  'هل تريد طرد {} من المجموعة؟': 'group_info.do_want_remove_value_group',
  'هندسة الإتصالات': 'legacy.communications_engineering',
  'هندسة الحاسوب': 'legacy.computer_engineering',
  'هندسة العمارة': 'legacy.architecture',
  'وثيقة systemSettings/cloudBilling غير موجودة': 'legacy.systemsettings_cloudbilling_document_does_not_exist',
  'وصلت للحد الأقصى': 'chat.maximum_reached',
  'يتطلب إدخال الرمز القديم': 'profile.requires_entering_old_pin',
  'يتطلب إدخال كلمة السر القديمة': 'profile.requires_entering_old_password',
  'يتم التسجيل الآن': 'legacy.recording',
  'يجب أن تكون كلمة السر الجديدة مختلفة عن القديمة': 'auth.new_password_must_different_old_one',
  'يجب إدخال خيارين على الأقل': 'chat.least_two_options_required',
  'يجب اختيار مدير من أعضاء المجموعة الحاليين': 'legacy.must_choose_admin_current_group_members',
  'يجب الاتصال بالإنترنت مرة واحدة لتفعيل هذا الجهاز بعد إدخال رمز PIN': 'pin.must_connect_internet_once_activate_device_after',
  'يجب التحقق من رمز PIN قبل تفعيل هذا الجهاز': 'legacy.must_verify_pin_before_activating_device',
  'يجب تسجيل الدخول': 'legacy.must_sign',
  'يجب تسجيل الدخول بحساب مسؤول قبل رفع الطلاب': 'legacy.sign_admin_account_before_uploading_students',
  'يجب تغيير كلمة السر المؤقتة قبل متابعة الدخول': 'auth.must_change_temporary_password_before_continuing',
  'يرجى تعبئة الحقول': 'validation.fill_required_fields',
  'يرجى تعبئة جميع الحقول': 'validation.fill_all_fields',
  'يمكنك إرسال الإشعارات فقط ضمن نطاق صلاحياتك': 'legacy.can_send_notifications_only_within_permission_scope',
  'يمكنك إعادة فتح الصفحة أو المحاولة لاحقًا.': 'group_info.reopen_page_try_again_later',
  'يمكنك التقريب والتحريك بحرية': 'legacy.can_zoom_move_freely',
  'يمكنك تعديل مستخدمي قسمك فقط': 'legacy.can_edit_only_users_department',
  'ينتهي في: {}': 'chat.ends_value',
};

String _translateMessage(String messageOrKey) {
  final clean = messageOrKey.trim();
  if (clean.isEmpty) return tr('errors.unexpected');
  final normalizedKey = _legacyTranslationKeyByMessage[clean] ?? clean;
  final translated = tr(normalizedKey);
  return translated == normalizedKey ? clean : translated;
}
